### ISSUE TITLE
L teachlead

### ISSUE THREAD

**Issue by Gerwoud** [SELab-2/UGent-3#382]

**Comment by miboelae** [comment]
༼ つ ◕_◕ ༽つ

**Comment by ArnoutAllaert** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⠶⣶⠾⠿⢿⣇⢸⣿⣶⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣾⣿⣶⣿⡀⠸⠀⠀⢸⣿⢿⡇⠀⠈⠉⢻⣿⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶
⡿⠿⠿⠻⠿⠛⠛⠿⠿⠛⠛⠛⠛⠻⠛⢻⣿⡿⠋⢹⣿⣿⡇⠀⠀⠀⠈⢿⣿⡇⠀⠀⠀⣿⡿⠿⠿⠿⢿⠿⠿⠿⠿⠿⠿⠿⠿⠿⢿⠿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣯⠀⠀⠀⠿⠟⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣦⠀⠀⠀⠀⢀⣀⣠⡤⠤⠤⠤⣄⣰⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣧⢀⡴⠚⠉⠁⠀⠀⠀⠀⠀⣠⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣦⣤⣀⣀⣤⣤⣤⣶⡿⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣭⣭⣿⣿⣿⣿⣿⠿⢷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⣀⣀⣴⣿⣿⣴⣿⣿⣿⡍⠁⠀⠀⠀⣴⣶⣤⣿⣿⣷⣦⣄⡀⠀⢀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣠⣴⣾⡿⠿⠿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⠿⠁⢀⣀⣀⡀⠻⢿⣿⣿⣿⣿⣿⠿⠿⠿⠿⠿⠿⠿⢿⣿⣶⣤⡀⠀⠀⠀⠀
⠀⠀⠀⣠⣾⡿⠋⠁⠀⠀⠀⠀⠀⠀⠀⢈⣿⡟⣋⡀⠀⠀⢰⡇⠀⠀⢸⠀⠀⠈⠉⠛⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣿⣆⠀⠀⠀
⠀⠀⢰⣿⡟⠀⠀⠀⠀⠀⠀⢀⣀⣀⣤⣾⠋⣼⣿⣿⣆⠀⢸⡇⠀⠀⢸⠀⢀⣶⣿⣷⡘⣿⡀⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠹⣿⣆⠀⠀
⠀⠀⣿⣿⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⡇⠀⠀⠓⠺⢟⣀⣸⠃⠀⠀⢸⣀⣺⠿⠤⠈⠁⠘⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⢻⣿⠀⠀
⠀⠀⣿⡏⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣷⣶⣶⣿⡋⠁⠀⠀⠀⠀⠈⠉⠙⢿⣶⣶⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⣻⣿⡿⠿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣶⣶⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⠟⠃⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⣴⣿⣿⣧⡀⠀⠀⢸⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⢸⡇⠀⠀⢀⡴⠻⣿⣷⡀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣷⣦⣼⣀⠀⠀⠀⠀⠀⣸⠀⠀⠀⠀⠀⢸⣀⣤⠶⠋⠀⠀⣿⣿⣿⡄⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⢿⠟⠛⠛⠒⠻⠒⠒⠛⠛⠋⠉⠉⠀⠀⠀⠀⢸⣿⣿⣿⣿⡄⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠻⣿⣿⣿⣿⣿⣟⡛⠛⠁⠀⠀⠘⣠⣴⣾⣿⡗⢸⣿⣶⣤⣤⣄⠀⠀⠀⠀⣀⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⠘⢿⣿⣿⣿⣟⠳⢦⣄⣀⡀⠋⠉⠙⠛⠻⢧⣿⠟⠉⠁⠀⠀⣙⣠⡴⠞⣻⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⣹⣿⣿⣿⣦⡀⠀⣹⠙⠓⠒⠒⠒⠲⢶⡷⠖⠒⠒⠚⠋⢹⠁⢀⣴⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⣇⠀⠀⠀⠀⠀⢠⣿⠻⣿⣿⣿⣿⣦⣁⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⢈⣶⣿⣿⣿⣿⠟⠛⣿⡀⠀⠀⠀⠀⠀⢸⣿⠀⠀
⠀⠀⣿⣿⡀⠀⠀⠀⢀⣿⣇⠀⠈⠻⣿⣿⣿⣿⣿⣶⣦⣤⣤⣤⣬⣤⣤⣤⣤⣶⣾⣿⣿⣿⡿⠟⠁⠀⠀⣿⣇⠀⠀⠀⠀⠀⣾⣿⠀⠀
⠀⠀⢿⣿⣷⡀⠀⠀⣼⡟⠙⠻⢦⣤⣀⠙⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠉⢀⣀⣴⠶⠟⠉⢿⡆⠀⠀⢀⣼⣿⣿⠀⠀
⠀⠀⠘⢿⣿⣿⣦⣴⡿⠀⠀⠀⠀⠈⠙⠛⠶⣦⣄⣈⠛⠿⣿⣿⣿⣿⣿⣿⠿⢋⣁⣤⠶⠾⠛⠉⠀⠀⠀⠀⠸⣿⣀⣴⣾⣿⣿⠃⠀⠀
⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠉⠛⠛⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠟⠛⠉⠀⠀⠀⠀⠀⠀
