### ISSUE TITLE
delete course create button for students

### ISSUE THREAD

**Issue by ArnoutAllaert** [SELab-2/UGent-3#385]
Currently a student has the option to create a new course. However the server (luckily) returns 403 forbidden, so i suggest removing the create button for students.
![image](https://github.com/SELab-2/UGent-3/assets/43027876/979fd611-7d6e-4ac7-9ab6-6f932d00d839)

**Comment by Gerwoud** [comment]
Feel free to open a PR for this :smile: the project is op source after all!

**Comment by ArnoutAllaert** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣠⡶⢶⣿⣿⣶⣦⢠⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⠟⣿⣼⡇⠀⠀⠀⢸⣿⣾⡏⠙⠻⢷⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡋⠀⠀⢿⣿⡇⠀⠀⠀⠸⢿⡿⠁⠀⠀⣾⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣷⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣶⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⣧⠀⠀⠀⢀⣀⣀⣀⣀⣀⣀⠀⢠⣿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⢷⣦⣄⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⢻⣧⡶⢟⠛⠛⠉⠉⠉⣻⣿⣟⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣄⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢼⣿⣿⣼⣿⣿⣿⡇⠀⠀⠀⠀⠿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣆⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⡀⠀⠀⠸⣿⣿⣿⠿⠛⠋⠀⣴⠉⠉⠙⡆⠀⠉⠉⠛⢻⣏⠀⠀⠀⠀⣠⡾⠟⠛⠻⣷⡄⠀⠀⠀⠀⠀⠀⢸⣿⠀
⢀⣤⣶⡶⠿⠿⠿⠿⠿⠿⠿⡧⠀⠀⠀⠀⠀⠀⠀⣼⡟⠛⠛⠻⣷⡀⠀⢰⡟⣡⣦⣄⠀⠀⣿⠀⠀⠀⣿⠀⢠⣾⣿⣦⢻⣆⠀⠀⢰⣿⠁⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⢸⣿⠀
⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡄⠀⠀⠀⢸⣿⣠⡿⠑⠛⣛⣿⣧⠀⢻⠀⠀⠀⢹⣀⣿⠭⠖⠈⢠⣿⣷⣶⣾⣿⠀⠀⠀⢠⣿⣁⣀⣀⣀⣀⠀⠀⢸⣿⠀
⠀⢿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⣀⣀⣹⣷⠀⠀⠀⣸⣿⣿⣿⣆⠀⢉⣩⡾⠟⠋⠀⠀⠀⠈⠋⠛⢿⣦⣤⣼⣿⣿⣿⣿⣿⣇⠀⠀⢸⣿⣿⣿⣛⠛⠛⠿⣶⣼⣿⠀
⠀⠈⠻⣿⣷⣤⡀⠀⠀⠀⠀⣠⣶⠿⠛⠋⣉⣭⠿⢿⣿⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣤⣤⣤⣤⣶⣶⣾⣿⣿⣿⣿⣿⣿⠿⠛⠋⠙⠀⠀⠈⠙⢧⡀⠈⠛⣦⠀⠈⠻⣿⡀
⠀⠀⠀⠈⠙⢿⣿⣷⣤⣀⣼⡟⠁⠀⣠⠞⠁⠀⣴⠋⠀⠀⠀⠈⠉⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⣿⠟⢻⡿⠀⠀⠀⠀⠀⠀⠀⠀⠈⣷⠀⠀⠸⡇⠀⠀⢻⡇
⠀⠀⠀⠀⠀⠀⠈⠙⠿⣿⣿⠃⠀⢀⡏⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⣿⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⣿⠀⢸⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⢀⡟⠀⠀⣾⡇
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⡆⠀⠸⣇⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⢹⠀⠀⠀⠀⠀⠘⣧⠀⠀⠀⠀⠀⢻⠀⣸⣿⡄⠀⠀⠀⠀⠀⠀⠀⢰⠇⠀⢀⡼⠃⢀⣴⣿⠁
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣷⣄⠀⠹⣆⠀⠀⢷⡀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣄⣸⡆⠀⠀⠀⠀⠀⣿⠀⠀⠀⣀⣠⣼⣾⣿⣿⣿⣶⣤⣤⣤⣀⣀⣴⣋⣠⣴⣻⣥⣶⠿⢻⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡏⠛⠿⣶⣭⣷⣤⣤⣷⣤⣤⣤⣤⣴⣶⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠛⠛⠛⠛⠛⠛⠉⠉⠀⠀⢸⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠈⠉⠉⠙⠛⠋⠉⣹⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡿⠀⠈⠙⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⢻⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡇⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⢷⣄⡀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠀⠀⢀⣠⡼⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡀⠀⠀⠀⠀⠀⠀⠀⣾⠇⠀⠈⠙⠳⢶⣤⣀⠀⠀⠀⠈⠉⠛⠻⠿⠿⠿⠿⠛⠉⠀⠀⣀⣠⡴⠞⠛⠁⠀⢹⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡟⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣷⡀⠀⠀⠀⠀⠀⣼⡟⠀⠀⠀⠀⠀⠀⠀⠉⠛⠳⠶⢤⣤⣤⣀⣀⣠⣤⣤⡴⠶⠞⠛⠉⠁⠀⠀⠀⠀⠀⠀⢿⣇⠀⠀⠀⠀⠀⠀⢀⣴⣿⠁⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣷⣤⣄⣀⣰⣿⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣉⣉⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣈⣿⣄⣀⣀⣀⣤⣶⣿⡿⠃⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠋⠀⠀⠀⠀
