### ISSUE TITLE
REFACTOR NAAR SPRING

### ISSUE THREAD

**Issue by ALBERICLOOS** [SELab-2/UGent-3#388]
SPRING >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PYTHON

**Comment by Gerwoud** [comment]
Why am I assigned? I don't see any reason for this.
Also I don't really think there's value to changing our backend language this late in the project, this should've been considered earlier if we wanted to do this.
@AronBuzogany you should know beter than to confuse me with unachievable issues when there is still other work to be done.

**Comment by AronBuzogany** [comment]
@Gerwoud Don't underestimate yourself! There are 2 days left until the deadline. You can do this, I believe in you!

**Comment by EwoutV** [comment]
@Gerwoud I also believe in you 😄 Low priority maintainers unite 💪

**Comment by Gerwoud** [comment]
Also @ALBERICLOOS if you create a issues please select the appropriate tags.

**Comment by ALBERICLOOS** [comment]
@Gerwoud stop crying like a bebe
